name: Deploy microservice

on:
  #
  # Deploys the microservice on push to the main branch of this code repository.
  #
  push:
    branches:
      - main

  #
  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  #
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_UN: ${{ secrets.ACR_UN }}
      ACR_PW: ${{ secrets.ACR_PW  }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      # Checkout the repository.
      - uses: actions/checkout@v3

      # Ensure all scripts have execution permission.
      - name: Make all scripts executable
        run: chmod +x ./scripts/*.sh
        
      #
      # Builds the Docker image.
      #
      - name: Build Docker image
        run: ./scripts/build-image.sh

      #
      # Publishes the Docker image to the container registry.
      #
      - name: Push Docker image
        run: ./scripts/push-image.sh

      #
      # Installs kubectl and connects it to the cluster using KUBE_CONFIG secret.
      #
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.31.0

      #
      # Deploy the microservice using kubectl.
      #
      - name: Deploy to AKS
        run: ./scripts/deploy.sh
